# Copyright 2026 Limx Dynamics
"""SmolVLA on all 50 RoboTwin tasks, clean/randomized mixed 1:1.

Absolute 14D joint actions, mean/std normalization and native 50-step
prediction; replan after 10 actions. Two balanced epochs are a starting
budget, not a validated optimum. Statistics are computed from these data.
The base SmolVLA checkpoint and SmolVLM2 tokenizer must be installed
under checkpoints/. Evaluate random scenes with eval.task_suite_name=random.
"""

_DATA_ROOTS = [
    'datasets/robotwin_clean_lerobotv2.1',
    'datasets/robotwin_randomized_lerobotv2.1',
]
_TOKENIZER_PATH = './checkpoints/SmolVLM2-500M-Video-Instruct'

_TASK_LIST = [
    'adjust_bottle',
    'beat_block_hammer',
    'blocks_ranking_rgb',
    'blocks_ranking_size',
    'click_alarmclock',
    'click_bell',
    'dump_bin_bigbin',
    'grab_roller',
    'handover_block',
    'handover_mic',
    'hanging_mug',
    'lift_pot',
    'move_can_pot',
    'move_pillbottle_pad',
    'move_playingcard_away',
    'move_stapler_pad',
    'open_laptop',
    'open_microwave',
    'pick_diverse_bottles',
    'pick_dual_bottles',
    'place_a2b_left',
    'place_a2b_right',
    'place_bread_basket',
    'place_bread_skillet',
    'place_burger_fries',
    'place_can_basket',
    'place_cans_plasticbox',
    'place_container_plate',
    'place_dual_shoes',
    'place_empty_cup',
    'place_fan',
    'place_mouse_pad',
    'place_object_basket',
    'place_object_scale',
    'place_object_stand',
    'place_phone_stand',
    'place_shoe',
    'press_stapler',
    'put_bottles_dustbin',
    'put_object_cabinet',
    'rotate_qrcode',
    'scan_object',
    'shake_bottle',
    'shake_bottle_horizontally',
    'stack_blocks_three',
    'stack_blocks_two',
    'stack_bowls_three',
    'stack_bowls_two',
    'stamp_seal',
    'turn_switch',
]

model = dict(
    type='SmolVLAFlowMatching',
    action_in_proj=dict(
        type='LinearProjector',
        in_dim=32,
        out_dim=720,
    ),
    action_out_proj=dict(
        type='LinearProjector',
        in_dim=720,
        out_dim=32,
    ),
    action_time_mlp_in=dict(
        type='LinearProjector',
        in_dim=1440,
        out_dim=720,
    ),
    action_time_mlp_out=dict(
        type='LinearProjector',
        in_dim=720,
        out_dim=720,
    ),
    add_image_special_tokens=False,
    chunk_size=50,
    freeze_vlm_backbone=False,
    llm_expert=dict(
        type='SmolVLMExpert',
        attention_bias=False,
        attention_mode='cross_attn',
        head_dim=64,
        hidden_act='silu',
        hidden_size=720,
        intermediate_size=-1,
        max_position_embeddings=8192,
        num_attention_heads=15,
        num_hidden_layers=16,
        num_key_value_heads=5,
        rms_norm_eps=1e-05,
        self_attn_every_n_layers=2,
        torch_dtype='bfloat16',
        vlm_kv_dim=320,
        vocab_size=49280,
    ),
    max_action_dim=32,
    name_mapping={
        'action_in_proj.projector': 'model.action_in_proj',
        'action_out_proj.projector': 'model.action_out_proj',
        'action_time_mlp_in.projector': 'model.action_time_mlp_in',
        'action_time_mlp_out.projector': 'model.action_time_mlp_out',
        'llm_expert.expert': 'model.vlm_with_expert.lm_expert',
        'state_proj.projector': 'model.state_proj',
        'vlm_backbone.vlm': 'model.vlm_with_expert.vlm.model',
    },
    num_steps=10,
    ori_action_dim=14,
    pretrained_name_or_path='./checkpoints/smolvla_base/model.safetensors',
    state_proj=dict(
        type='LinearProjector',
        in_dim=32,
        out_dim=960,
    ),
    vlm_backbone=dict(
        type='SmolVLMBackbone',
        num_vlm_layers=16,
        scale_factor=4,
        text_config=dict(
            head_dim=64,
            hidden_act='silu',
            hidden_size=960,
            intermediate_size=2560,
            max_position_embeddings=8192,
            num_attention_heads=15,
            num_hidden_layers=32,
            num_key_value_heads=5,
            rms_norm_eps=1e-05,
            vocab_size=49280,
        ),
        torch_dtype='bfloat16',
        vision_config=dict(
            hidden_act='gelu_pytorch_tanh',
            hidden_size=768,
            image_size=512,
            intermediate_size=3072,
            layer_norm_eps=1e-06,
            num_attention_heads=12,
            num_hidden_layers=12,
            patch_size=16,
        ),
    ),
)

inference_model = model.copy()

train_dataloader = dict(
    dataset=dict(
        type='DistributedBalancedRepeatingDataset',
        auto_compute_statistics=dict(profile='absolute', ),
        datasets=dict(
            type='ParquetDataset',
            action_key='action',
            action_window_size=50,
            data_root_path=_DATA_ROOTS,
            statistic_name='robotwin_all',
            supervise_terminal_padding=True,
            transforms=[
                dict(
                    type='ProcessParquetInputs',
                    name_mappings={
                        'actions': ['actions'],
                        'observation.state': ['states'],
                    },
                    parquet_keys=[
                        'observation.state',
                        'timestamp',
                        'actions',
                        'info',
                        'stats',
                        'action_masks',
                    ],
                    video_backend='pyav',
                    video_keys=[
                        'observation.images.cam_high',
                        'observation.images.cam_left_wrist',
                        'observation.images.cam_right_wrist',
                    ],
                ),
                dict(
                    type='NormalizeStatesAndActions',
                    output_dtype='float32',
                    action_dim=32,
                    action_key='action',
                    norm_type='mean_std',
                    state_dim=32,
                    state_key='proprio',
                ),
                dict(
                    type='ParquetPrompter',
                    add_new_line=True,
                    use_conversation=False,
                ),
                dict(
                    type='ProcessPrompts',
                    max_len=48,
                    tokenizer=dict(
                        type='PretrainedTokenizer',
                        model_path=_TOKENIZER_PATH,
                    ),
                ),
                dict(
                    type='ResizeImagesWithPad',
                    height=512,
                    pad_direction='top-left',
                    width=512,
                ),
                dict(type='SimpleNormalizeImages', ),
            ],
            use_delta=False,
            window_start_idx=0,
        ),
        name_mappings={
            'action': ['action'],
            'observation.state': ['proprio'],
        },
        reshuffle_each_epoch=True,
        sampling_unit='episode',
        sampling_weights=[1.0, 1.0],
        seed=42,
        shuffle=True,
        statistic_keys=['observation.state', 'timestamp', 'action'],
        statistic_name='robotwin_all',
    ),
    per_device_batch_size=16,
    per_device_num_workers=4,
)

runner = dict(
    type='FSDPTrainRunner',
    change_key_name=False,
    collator=dict(
        type='DictCollator',
        keys=[
            'states',
            'timestamp',
            'images',
            'img_masks',
            'lang_tokens',
            'lang_masks',
            'actions',
            'action_masks',
        ],
        meta_keys=['task_description', 'prompt', 'info', 'stats'],
    ),
    deterministic_algorithms=False,
    enable_gradient_checkpointing=True,
    enable_mixed_precision_training=True,
    grad_accumulation_steps=2,
    keep_params_fp32=True,
    lr_scheduler=dict(
        type='linear-warmup+cosine-decay',
        min_lr=2.5e-06,
        warmup_ratio=0.05,
    ),
    max_epochs=2,
    max_grad_norm=10.0,
    max_keep_ckpts=3,
    max_steps=None,
    metric=dict(
        type='VLAMetric',
        active_trackers=('jsonl', 'wandb'),
        run_dir='work_dirs',
        window_size=100,
    ),
    mixed_precision_dtype='bf16',
    optimizer=dict(
        type='AdamW',
        betas=(0.9, 0.95),
        eps=1e-08,
        foreach=False,
        fused=True,
        lr=0.0001,
        weight_decay=1e-10,
        weight_decay_all_params=True,
    ),
    sampler=None,
    save_epoch_interval=1,
    save_iter_interval=10000000,
    seed=42,
    sharding_strategy='full-shard',
    tokenizer=dict(
        type='PretrainedTokenizer',
        model_path=_TOKENIZER_PATH,
    ),
)

eval = dict(
    type='RobotwinEvalRunner',
    dataset=dict(
        type='PrivateInferenceDataset',
        img_keys=['cam_high', 'cam_left_wrist', 'cam_right_wrist'],
        inject_model_path=False,
        transforms=[
            dict(
                type='NormalizeStatesAndActions',
                output_dtype='float32',
                action_dim=32,
                action_key='action',
                norm_type='mean_std',
                state_dim=32,
                state_key='proprio',
            ),
            dict(
                type='ParquetPrompter',
                add_new_line=True,
                use_conversation=False,
            ),
            dict(
                type='ProcessPrompts',
                max_len=48,
                tokenizer=dict(
                    type='PretrainedTokenizer',
                    model_path=_TOKENIZER_PATH,
                ),
            ),
            dict(
                type='ResizeImagesWithPad',
                height=512,
                pad_direction='top-left',
                width=512,
            ),
            dict(type='SimpleNormalizeImages', ),
        ],
    ),
    denormalize_action=dict(
        type='DenormalizePrivateAction',
        action_dim=14,
        norm_type='mean_std',
        statistic_name='robotwin_all',
    ),
    eval_chunk_size=10,
    instruction_type='unseen',
    mixed_precision_dtype='bf16',
    model_family='smolvla',
    num_trials_per_task=100,
    seed=7,
    task_list=_TASK_LIST,
    task_suite_name='clean',
    unnorm_key='robotwin_all',
)
