# Copyright 2026 Limx Dynamics
"""DiT4DiT on all 50 RoboTwin tasks, clean/randomized mixed 1:1.

Initialize Cosmos from the local base model; train a new 14D joint action
head (padded to 16), with 16-step predictions and 10 executed actions.
The 14D state uses interleaved sin/cos padded to 32. All three cameras
are tiled into a 336x224 video; train and eval share [-1, 1] image inputs.
Two balanced epochs are an initial budget, not a source RoboTwin result.
Evaluate random scenes with eval.task_suite_name=random.
"""

_DATA_ROOTS = [
    'datasets/robotwin_clean_lerobotv2.1',
    'datasets/robotwin_randomized_lerobotv2.1',
]
_TOKENIZER_PATH = './checkpoints/Cosmos-Predict2.5-2B/tokenizer'

_TASK_LIST = [
    'adjust_bottle',
    'beat_block_hammer',
    'blocks_ranking_rgb',
    'blocks_ranking_size',
    'click_alarmclock',
    'click_bell',
    'dump_bin_bigbin',
    'grab_roller',
    'handover_block',
    'handover_mic',
    'hanging_mug',
    'lift_pot',
    'move_can_pot',
    'move_pillbottle_pad',
    'move_playingcard_away',
    'move_stapler_pad',
    'open_laptop',
    'open_microwave',
    'pick_diverse_bottles',
    'pick_dual_bottles',
    'place_a2b_left',
    'place_a2b_right',
    'place_bread_basket',
    'place_bread_skillet',
    'place_burger_fries',
    'place_can_basket',
    'place_cans_plasticbox',
    'place_container_plate',
    'place_dual_shoes',
    'place_empty_cup',
    'place_fan',
    'place_mouse_pad',
    'place_object_basket',
    'place_object_scale',
    'place_object_stand',
    'place_phone_stand',
    'place_shoe',
    'press_stapler',
    'put_bottles_dustbin',
    'put_object_cabinet',
    'rotate_qrcode',
    'scan_object',
    'shake_bottle',
    'shake_bottle_horizontally',
    'stack_blocks_three',
    'stack_blocks_two',
    'stack_bowls_three',
    'stack_bowls_two',
    'stamp_seal',
    'turn_switch',
]

model = dict(
    type='DiT4DiTVLA',
    freeze_vlm_backbone=False,
    repeated_diffusion_steps=4,
    vla_head=dict(
        type='DiT4DiTActionHead',
        action_dim=16,
        action_horizon=16,
        action_model_type='DiT-B',
        add_pos_embed=True,
        diffusion_model_cfg=dict(
            cross_attention_dim=2048,
            dropout=0.2,
            final_dropout=True,
            interleave_self_attention=True,
            norm_type='ada_norm',
            num_layers=16,
            output_dim=2560,
            positional_embeddings=None,
        ),
        future_action_window_size=15,
        hidden_size=2560,
        max_seq_len=1024,
        noise_beta_alpha=1.5,
        noise_beta_beta=1.0,
        noise_s=0.999,
        num_inference_timesteps=4,
        num_timestep_buckets=1000,
        ori_action_dim=14,
        state_dim=32,
    ),
    vlm_backbone=dict(
        type='Cosmos25Backbone',
        base_model='./checkpoints/Cosmos-Predict2.5-2B',
        conditional_frame_timestep=0.0001,
        detach_hidden_states=True,
        extract_layer=17,
        fixed_seed=None,
        flow_matching_high_sigma_min=None,
        flow_matching_high_sigma_ratio=None,
        flow_matching_time_distribution='uniform',
        frozen_submodules=['text_encoder', 'vae'],
        fsdp_min_num_params=0,
        future_loss_type='flow_matching',
        local_files_only=True,
        num_frames_out=9,
        num_inference_steps=1,
        revision='diffusers/base/post-trained',
        split_future_frames=True,
        torch_dtype='bf16',
        trainable=True,
    ),
)

inference_model = dict(
    model,
    init_empty_weights=True,
    vlm_backbone=dict(model['vlm_backbone'], load_pretrained_weights=False))

train_dataloader = dict(
    dataset=dict(
        type='DistributedBalancedRepeatingDataset',
        auto_compute_statistics=dict(profile='absolute', ),
        datasets=dict(
            type='ParquetDataset',
            action_key='action',
            action_window_size=16,
            data_root_path=_DATA_ROOTS,
            frame_sample_stride=2,
            frame_window_size=9,
            statistic_name='robotwin_all',
            supervise_terminal_padding=True,
            transforms=[
                dict(
                    type='ProcessParquetInputs',
                    name_mappings={
                        'actions': ['actions'],
                        'observation.state': ['states'],
                    },
                    parquet_keys=[
                        'observation.state',
                        'timestamp',
                        'actions',
                        'info',
                        'stats',
                        'action_masks',
                    ],
                    video_backend='pyav',
                    video_keys=[
                        'observation.images.cam_high',
                        'observation.images.cam_left_wrist',
                        'observation.images.cam_right_wrist',
                    ],
                ),
                dict(
                    type='ProcessCosmos25Prompt',
                    input_key='task_description',
                    remove_input_key=True,
                    tokenizer=dict(
                        type='PretrainedTokenizer',
                        model_max_length=512,
                        model_path=_TOKENIZER_PATH,
                    ),
                ),
                dict(
                    type='ResizeImages',
                    backend='torch',
                    height=224,
                    output_layout='flattened_chw',
                    scale_divisor=255.0,
                    width=224,
                ),
                dict(
                    type='NormalizeImages',
                    means=[0.5, 0.5, 0.5],
                    stds=[0.5, 0.5, 0.5],
                ),
                dict(
                    type='PrepareVideo',
                    bottom_height_ratio=0.5,
                    bottom_views=(1, 2),
                    combine_view_masks=True,
                    frame_window_size=9,
                    num_views=3,
                    tile_direction='top_bottom_pair',
                    top_view=0,
                ),
                dict(
                    type='SinCosKeys',
                    backend='torch',
                    expand_axis=0,
                    interleave=True,
                    keys=['states'],
                    target_dims=dict(states=32, ),
                ),
                dict(
                    type='NormalizeStatesAndActions',
                    action_dim=16,
                    action_key='action',
                    norm_type='min_max',
                    normalization_epsilon=1e-06,
                    output_dtype='float32',
                    state_dim=None,
                    state_key='proprio',
                    state_norm_type='none',
                ),
                # Keep temporal padding masks while masking the two padded
                # action dimensions expected by the 16D ActionDiT head.
                dict(
                    type='PrepareStateActionTargets',
                    state_history_length=1,
                    action_horizon=16,
                    valid_action_dim=14,
                ),
            ],
            use_delta=False,
            window_start_idx=0,
        ),
        name_mappings={
            'action': ['action'],
            'observation.state': ['proprio'],
        },
        reshuffle_each_epoch=True,
        sampling_unit='episode',
        sampling_weights=[1.0, 1.0],
        seed=42,
        shuffle=True,
        statistic_keys=['observation.state', 'timestamp', 'action'],
        statistic_name='robotwin_all',
    ),
    per_device_batch_size=2,
    per_device_num_workers=4,
)

runner = dict(
    type='FSDPTrainRunner',
    change_key_name=False,
    collator=dict(
        type='DictCollator',
        keys=[
            'states',
            'timestamp',
            'images',
            'img_masks',
            'actions',
            'action_masks',
            'frame_masks',
            'lang_tokens',
            'lang_masks',
        ],
        meta_keys=['info', 'stats'],
    ),
    enable_gradient_checkpointing=False,
    enable_mixed_precision_training=True,
    grad_accumulation_steps=4,
    lr_scheduler=dict(
        type='linear-warmup+cosine-decay',
        min_lr=5e-07,
        warmup_ratio=0.05,
    ),
    max_epochs=2,
    max_grad_norm=1.0,
    max_keep_ckpts=3,
    max_steps=None,
    metric=dict(
        type='VLAMetric',
        active_trackers=('jsonl', 'wandb'),
        grad_accumulation_steps=4,
        run_dir='work_dirs',
        window_size=100,
    ),
    mixed_precision_dtype='bf16',
    optimizer=dict(
        type='AdamW',
        betas=(0.9, 0.95),
        eps=1e-08,
        lr=3e-05,
        paramwise_learning_rate={
            'vla_head': 0.0001,
            'vlm_backbone.transformer': 1e-05,
        },
        weight_decay=1e-08,
        weight_decay_all_params=True,
    ),
    pre_fsdp_param_dtype='fp32',
    reduce_in_full_precision=False,
    sampler=None,
    save_epoch_interval=1,
    save_iter_interval=10000000,
    seed=42,
    sharding_strategy='global-shard-grad-op',
    tokenizer=dict(
        type='PretrainedTokenizer',
        model_max_length=512,
        model_path=_TOKENIZER_PATH,
    ),
)

eval = dict(
    type='RobotwinEvalRunner',
    dataset=dict(
        type='PrivateInferenceDataset',
        img_keys=['cam_high', 'cam_left_wrist', 'cam_right_wrist'],
        inject_model_path=False,
        transforms=[
            dict(
                type='ProcessCosmos25Prompt',
                input_key='task_description',
                remove_input_key=True,
                tokenizer=dict(
                    type='PretrainedTokenizer',
                    model_max_length=512,
                    model_path=_TOKENIZER_PATH,
                ),
            ),
            dict(
                type='ResizeImages',
                backend='torch',
                height=224,
                output_layout='flattened_chw',
                scale_divisor=255.0,
                width=224,
            ),
            dict(
                type='NormalizeImages',
                means=[0.5, 0.5, 0.5],
                stds=[0.5, 0.5, 0.5],
            ),
            dict(
                type='PrepareVideo',
                bottom_height_ratio=0.5,
                bottom_views=(1, 2),
                combine_view_masks=True,
                frame_window_size=1,
                num_views=3,
                tile_direction='top_bottom_pair',
                top_view=0,
            ),
            dict(
                type='SinCosKeys',
                backend='torch',
                expand_axis=0,
                interleave=True,
                keys=['states'],
                target_dims=dict(states=32, ),
            ),
            dict(
                type='NormalizeStatesAndActions',
                action_dim=16,
                action_key='action',
                norm_type='min_max',
                normalization_epsilon=1e-06,
                output_dtype='float32',
                state_dim=None,
                state_key='proprio',
                state_norm_type='none',
            ),
            dict(
                type='PrepareStateActionTargets',
                state_history_length=1,
                action_horizon=16,
                valid_action_dim=14,
            ),
        ],
    ),
    denormalize_action=dict(
        type='DenormalizePrivateAction',
        action_dim=14,
        norm_type='min_max',
        statistic_name='robotwin_all',
    ),
    eval_chunk_size=10,
    instruction_type='unseen',
    mixed_precision_dtype='bf16',
    model_family='dit4dit',
    num_trials_per_task=100,
    seed=7,
    task_list=_TASK_LIST,
    task_suite_name='clean',
    unnorm_key='robotwin_all',
)
